// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHBjGGi5tQfJNn3pJX6RvBMOlWqHfEhY',
    appId: '1:653200103053:web:b68efca49f04849c8b34c4',
    messagingSenderId: '653200103053',
    projectId: 'agrofi',
    authDomain: 'agrofi.firebaseapp.com',
    storageBucket: 'agrofi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJPCY9PoPP-Jc3RepBpdutSnQW6W1tgzU',
    appId: '1:653200103053:android:57d7d5b442f1eb7a8b34c4',
    messagingSenderId: '653200103053',
    projectId: 'agrofi',
    storageBucket: 'agrofi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVkYXegXl0WPwGPZjuNvccVmX0BlQE_4',
    appId: '1:653200103053:ios:982ae3eca5e6d06d8b34c4',
    messagingSenderId: '653200103053',
    projectId: 'agrofi',
    storageBucket: 'agrofi.appspot.com',
    iosClientId: '653200103053-ukdimbs6a9lnfm5hhglbl1b8arrnjf4g.apps.googleusercontent.com',
    iosBundleId: 'africa.agrofi.agrofi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVkYXegXl0WPwGPZjuNvccVmX0BlQE_4',
    appId: '1:653200103053:ios:982ae3eca5e6d06d8b34c4',
    messagingSenderId: '653200103053',
    projectId: 'agrofi',
    storageBucket: 'agrofi.appspot.com',
    iosClientId: '653200103053-ukdimbs6a9lnfm5hhglbl1b8arrnjf4g.apps.googleusercontent.com',
    iosBundleId: 'africa.agrofi.agrofi',
  );
}
